#Service
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx

---
# Secret
apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
  labels:
    app: nginx
type: Opaque
data:
#  API_VALUE_123 is the Value for the below secret
  API_KEY: QVBJX1ZBTFVFXzEyMw==

---
#Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-sa
  labels:
    app: nginx
imagePullSecrets:
  - name: wh-test-docker-registry

---
#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: ravienggtoo/wh-nginx:1
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: nginx-secret
                  key: API_KEY
                  optional: false
          ports:
            - containerPort: 80
          resources:
#            limits:
#              cpu: 500m
#              memory: 1Gi
            requests:
              cpu: 200m
              memory: 0.5Gi
          volumeMounts:
            - name: apikey-secretmount
              mountPath: "/tmp/apikey"
              readOnly: true
          imagePullPolicy: Always
      securityContext:
        runAsUser: 101
        runAsGroup: 101
      serviceAccountName: nginx-sa
      volumes:
        - name: apikey-secretmount
          secret:
            secretName: nginx-secret

---
#Horizontal Pod AutoScaling
#CPU
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-hpa-cpu
  labels:
    app: nginx
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50

---
#Horizontal Pod AutoScaling
#Memory
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-hpa-mem
  labels:
    app: nginx
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageValue: 10Mi

---
#Pod Distribution Budget
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nginx-pdb
  labels:
    app: nginx
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: nginx